apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 35
  metrics:
  - type: External
    external:
      metric:
        name: custom.googleapis.com|nginx_ingress_controller_nginx_process_requests_total
      target:
        type: Value
        value: 3
  - type: External
    external:
      metric:
        name: custom.googleapis.com|nginx_ingress_controller_nginx_process_connections_total
      target:
        type: Value
        value: 2
